import {useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {deleteOrder,getAdminOrders,getAdminProducts,updateOrder} from "../../api/admin";
import {ErrorBox,LoadingBox,Modal,PageHeader,StatusBadge} from "../../components/admin/AdminUI";
const statuses=[["","كل الحالات"],["new","جديد"],["confirmed","تم التأكيد"],["shipped","تم الشحن"],["delivered","تم التسليم"],["cancelled","ملغي"]];
const gov=["القاهرة","الجيزة","الإسكندرية","الدقهلية","دمياط","الشرقية","الغربية","المنوفية","القليوبية","البحيرة","كفر الشيخ","بورسعيد","الإسماعيلية","السويس","الفيوم","بني سويف","المنيا","أسيوط","سوهاج","قنا","الأقصر","أسوان","البحر الأحمر","الوادي الجديد","مطروح","شمال سيناء","جنوب سيناء"];
export default function Orders(){
 const qc=useQueryClient(),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[page,setPage]=useState(1),[selected,setSelected]=useState(null),[form,setForm]=useState(null);
 const q=useQuery({queryKey:["admin-orders",search,status,page],queryFn:()=>getAdminOrders({search,status,page})});
 const pq=useQuery({queryKey:["admin-products"],queryFn:getAdminProducts});
 const save=useMutation({mutationFn:({id,p})=>updateOrder(id,p),onSuccess:async()=>{await qc.invalidateQueries({queryKey:["admin-orders"]});await qc.invalidateQueries({queryKey:["admin-dashboard"]});setSelected(null);setForm(null)}});
 const del=useMutation({mutationFn:deleteOrder,onSuccess:async()=>{await qc.invalidateQueries({queryKey:["admin-orders"]});setSelected(null);setForm(null)}});
 if(q.isLoading)return <LoadingBox/>;if(q.isError)return <ErrorBox message={q.error.message}/>;
 const open=o=>{setSelected(o);setForm({customerName:o.customer_name,phone:o.phone,governorate:o.governorate,address:o.address,productSlug:o.product_slug,quantity:o.quantity,unitPrice:o.unit_price,status:o.status,notes:o.notes||""})};
 return <div><PageHeader title="إدارة الطلبات" description={`${q.data.pagination.total} طلب`}/>
 <div className="mb-4 grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-[1fr_220px]"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="بحث بالاسم أو الهاتف..." className="h-12 rounded-xl border px-4"/><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="h-12 rounded-xl border bg-white px-4">{statuses.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></div>
 <div className="overflow-hidden rounded-2xl border bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-right text-sm"><thead className="bg-zinc-50"><tr><th className="p-4">#</th><th className="p-4">العميل</th><th className="p-4">الهاتف</th><th className="p-4">المنتج</th><th className="p-4">المحافظة</th><th className="p-4">الإجمالي</th><th className="p-4">الحالة</th><th className="p-4">إجراء</th></tr></thead><tbody>{q.data.orders.map(o=><tr className="border-t" key={o.id}><td className="p-4">{o.order_number||o.id}</td><td className="p-4 font-bold">{o.customer_name}</td><td className="p-4">{o.phone}</td><td className="p-4">{o.product_name} × {o.quantity}</td><td className="p-4">{o.governorate}</td><td className="p-4">{o.total} جنيه</td><td className="p-4"><StatusBadge status={o.status}/></td><td className="p-4"><button onClick={()=>open(o)} className="rounded-lg bg-zinc-950 px-4 py-2 text-white">تعديل</button></td></tr>)}</tbody></table></div><div className="flex justify-between border-t p-4"><button disabled={page<=1} onClick={()=>setPage(page-1)}>السابق</button><b>{page} / {q.data.pagination.pages}</b><button disabled={page>=q.data.pagination.pages} onClick={()=>setPage(page+1)}>التالي</button></div></div>
 <Modal open={!!form} onClose={()=>setForm(null)} title={`تعديل الطلب ${selected?.order_number||""}`} width="max-w-4xl">{form&&<form onSubmit={e=>{e.preventDefault();save.mutate({id:selected.id,p:form})}} className="grid gap-4 sm:grid-cols-2">
 {[["customerName","اسم العميل"],["phone","الهاتف"],["quantity","الكمية"],["unitPrice","سعر الوحدة"]].map(([n,l])=><label key={n} className="grid gap-2"><b>{l}</b><input type={["quantity","unitPrice"].includes(n)?"number":"text"} value={form[n]} onChange={e=>setForm({...form,[n]:e.target.value})} className="h-12 rounded-xl border px-4"/></label>)}
 <label className="grid gap-2"><b>المحافظة</b><select value={form.governorate} onChange={e=>setForm({...form,governorate:e.target.value})} className="h-12 rounded-xl border bg-white px-4">{gov.map(g=><option key={g}>{g}</option>)}</select></label>
 <label className="grid gap-2"><b>المنتج</b><select value={form.productSlug} onChange={e=>{const p=pq.data?.products.find(x=>x.slug===e.target.value);setForm({...form,productSlug:e.target.value,unitPrice:p?.price||form.unitPrice})}} className="h-12 rounded-xl border bg-white px-4">{(pq.data?.products||[]).map(p=><option key={p.id} value={p.slug}>{p.name}</option>)}</select></label>
 <label className="grid gap-2"><b>الحالة</b><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="h-12 rounded-xl border bg-white px-4">{statuses.slice(1).map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label>
 <div className="rounded-xl bg-zinc-100 p-4"><small>الإجمالي</small><b className="block text-xl">{(+form.quantity||0)*(+form.unitPrice||0)} جنيه</b></div>
 <label className="grid gap-2 sm:col-span-2"><b>العنوان</b><textarea rows="3" value={form.address} onChange={e=>setForm({...form,address:e.target.value})} className="rounded-xl border p-4"/></label>
 <label className="grid gap-2 sm:col-span-2"><b>الملاحظات</b><textarea rows="3" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="rounded-xl border p-4"/></label>
 <button disabled={save.isPending} className="rounded-xl bg-zinc-950 p-4 font-black text-white sm:col-span-2">حفظ التعديلات</button><button type="button" onClick={()=>confirm("حذف الطلب؟")&&del.mutate(selected.id)} className="rounded-xl border border-red-300 p-3 text-red-700 sm:col-span-2">حذف الطلب</button>
 </form>}</Modal></div>;
}
